defaults:
    - override hydra/launcher: submitit_local

# environment
task: dog-run
obs: state

# evaluation
checkpoint: ???
eval_episodes: 1
eval_freq: 20000

# training
steps: 10_000_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
#buffer_size: 3_000

buffer_size: 3_000_000
exp_name: default
data_dir: ???

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
horizon_RLHF: 18
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 4
enc_dim: 512
num_channels: 64
mlp_dim: 1024
latent_dim: 1024
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: humanoid-bench
wandb_entity: robot-learning
wandb_silent: false
disable_wandb: true
save_csv: true

# misc
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???

# humanoid envs
policy_path: ???
mean_path: ???
var_path: ???
policy_type: ???
small_obs: ???

save_model: True
batch_size_RLHF: 32
batch_size_RLHF_eval: 8
early_stop: False
min_delta: 1e-3
patience: 10
reward_scale: 1.0
reward_bias: 0.0
clip_action: 0.999
reward_arch: '256-256'
orthogonal_init: False
activations: 'relu'
activation_final: 'none'
training: True
n_epochs: 2000 # 2000
eval_period: 5
balance: False
use_human_label: False